# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ian Hanken
name: ihanken
email: ihanken@bellsouth.net
location: Memphis, Tennessee
company: Froghat, LLC
company_url: http://froghat.github.io
github_url: https://github.com/ihanken
description: Ian Hanken's Personal Github Page.
favicon: favicon.png # Image must be in assets/images

url: http://ihanken.github.io # the base hostname & protocol for your site
repository: froghat

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: ihankengithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmarks

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [Swift, C, C++, Java, Javascript, SPICE, MATLAB, LaTeX, SQL, PHP]
skill_framework_keywords: [Xcode, Git, AWS, Parse, Eclipse]
skill_operating_system_keywords: [Windows 7/8/10, iOS, OS X]
